name: actions-workflow
on:
  pull_request:
  repository_dispatch:
    types: 'build'
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -all
      - name: Checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          ls -all
      - name: simple js action
        id: action1
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Lord Vader
      - name: log output
        run: echo "${{ steps.action1.outputs.time }}"