name: matrix
on:
  - push
jobs:
  node-version:
    strategy:
      matrix:
        node_version:
          - 6
          - 8
          - 10
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        exclude:
          - os: ubuntu-latest
            node_version: 6
        include:
          - os: ubuntu-latest
            is_ubuntu: true
    env:
      IS_UBUNTU: ${{matrix.is_ubuntu}}
    runs-on: ${{matrix.os}}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - name: log node version
        run: | 
          node -v
          echo $IS_UBUNTU
          echo ${{env.IS_UBUNTU}}
      - name: say ubuntu
        if: ${{env.IS_UBUNTU}}
        run: echo "i am ubuntu"